/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://y7xgi643kvcftcx27qqficjsj4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6zvmtqfgtrgwvntl6tvk4n5osq",
    "aws_cognito_identity_pool_id": "eu-central-1:0f6038b4-30a1-4f0d-9895-c987b487f28b",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_uuJ2GIRtu",
    "aws_user_pools_web_client_id": "4vsphu8ralpnca8a4mg0jkb9g8",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
