/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://ugulixrqbrdoffwf2oa5g4uddq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-es5wbz4yqjfo5djvqrkrp5imqq",
    "aws_cognito_identity_pool_id": "eu-central-1:caecfa99-1197-4cde-9ea9-4c743914ea6e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_aCpvnVcjN",
    "aws_user_pools_web_client_id": "3jl93qeqp8jke1v5jha550d2t2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
