-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.answer_likes FROM authenticated;
REVOKE ALL ON TABLE public.answer_likes FROM postgres;
REVOKE ALL ON TABLE public.answer_likes FROM service_role;
GRANT ALL ON TABLE public.answer_likes TO authenticated;

GRANT ALL ON TABLE public.answer_likes TO service_role;

GRANT ALL ON TABLE public.answer_likes TO postgres;

REVOKE ALL ON TABLE public.course_user FROM anon;
REVOKE ALL ON TABLE public.course_user FROM authenticated;
REVOKE ALL ON TABLE public.course_user FROM postgres;
REVOKE ALL ON TABLE public.course_user FROM service_role;
REVOKE ALL ON TABLE public.course_user FROM supabase_admin;
GRANT ALL ON TABLE public.course_user TO supabase_admin;

GRANT ALL ON TABLE public.course_user TO authenticated;

GRANT ALL ON TABLE public.course_user TO anon;

GRANT ALL ON TABLE public.course_user TO postgres;

GRANT ALL ON TABLE public.course_user TO service_role;

REVOKE ALL ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO postgres;

REVOKE ALL ON TABLE public.open_feedback FROM authenticated;
REVOKE ALL ON TABLE public.open_feedback FROM postgres;
REVOKE ALL ON TABLE public.open_feedback FROM service_role;
GRANT ALL ON TABLE public.open_feedback TO authenticated;

GRANT ALL ON TABLE public.open_feedback TO service_role;

GRANT ALL ON TABLE public.open_feedback TO postgres;

REVOKE ALL ON TABLE public.answers FROM authenticated;
REVOKE ALL ON TABLE public.answers FROM postgres;
REVOKE ALL ON TABLE public.answers FROM service_role;
GRANT ALL ON TABLE public.answers TO authenticated;

GRANT ALL ON TABLE public.answers TO service_role;

GRANT ALL ON TABLE public.answers TO postgres;

REVOKE ALL ON TABLE public.question_likes FROM authenticated;
REVOKE ALL ON TABLE public.question_likes FROM postgres;
REVOKE ALL ON TABLE public.question_likes FROM service_role;
GRANT ALL ON TABLE public.question_likes TO authenticated;

GRANT ALL ON TABLE public.question_likes TO service_role;

GRANT ALL ON TABLE public.question_likes TO postgres;

REVOKE ALL ON TABLE public.question_topic FROM authenticated;
REVOKE ALL ON TABLE public.question_topic FROM postgres;
REVOKE ALL ON TABLE public.question_topic FROM service_role;
GRANT ALL ON TABLE public.question_topic TO authenticated;

GRANT ALL ON TABLE public.question_topic TO service_role;

GRANT ALL ON TABLE public.question_topic TO postgres;

-- Changing the columns in a view requires dropping and re-creating the view.
-- This may fail if other objects are dependent upon this view,
-- or may cause procedural functions to fail if they are not modified to
-- take account of the changes.
DROP VIEW public.answer_performances;
CREATE OR REPLACE VIEW public.answer_performances
    AS
     SELECT course_user.id,
    answers.id AS answer_id,
    answers.answer_text,
    answers.created_at,
    ( SELECT count(*) AS count
           FROM answer_likes
          WHERE answer_likes.answer = answers.id) AS likes,
    questions.question_text
   FROM course_user
     JOIN answers ON answers.owner = course_user.user_id AND (( SELECT questions_1.course
           FROM questions questions_1
          WHERE answers.question = questions_1.id)) = course_user.course
     JOIN questions ON questions.id = answers.question AND questions.course = course_user.course;
GRANT ALL ON TABLE public.answer_performances TO anon;
GRANT ALL ON TABLE public.answer_performances TO postgres;
GRANT ALL ON TABLE public.answer_performances TO supabase_admin;
GRANT ALL ON TABLE public.answer_performances TO authenticated;
GRANT ALL ON TABLE public.answer_performances TO service_role;
