-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.topics
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name text COLLATE pg_catalog."default" NOT NULL,
    challenge_pool uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT topics_pkey PRIMARY KEY (id),
    CONSTRAINT topics_challenge_pool_fkey FOREIGN KEY (challenge_pool)
        REFERENCES public.challenge_pools (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.topics
    OWNER to postgres;

GRANT ALL ON TABLE public.topics TO anon;

GRANT ALL ON TABLE public.topics TO authenticated;

GRANT ALL ON TABLE public.topics TO postgres;

GRANT ALL ON TABLE public.topics TO service_role;
