-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.open_question_topic
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    open_question uuid NOT NULL,
    topic uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT open_question_topic_pkey PRIMARY KEY (id),
    CONSTRAINT open_question_topic_open_question_fkey FOREIGN KEY (open_question)
        REFERENCES public.open_questions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT open_question_topic_topic_fkey FOREIGN KEY (topic)
        REFERENCES public.topics (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.open_question_topic
    OWNER to postgres;

GRANT ALL ON TABLE public.open_question_topic TO anon;

GRANT ALL ON TABLE public.open_question_topic TO authenticated;

GRANT ALL ON TABLE public.open_question_topic TO postgres;

GRANT ALL ON TABLE public.open_question_topic TO service_role;
