-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY course_user_select_policy_for_course_member
    ON public.course_user
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() = user_id));

CREATE POLICY course_user_select_policy_for_course_owner
    ON public.course_user
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING ((auth.uid() IN ( SELECT courses.owner
   FROM courses
  WHERE (course_user.course = courses.id))));

DROP POLICY IF EXISTS cpu_select_policy_for_cp_owner ON public.course_user;

DROP POLICY IF EXISTS cpu_select_policy_for_cp_member ON public.course_user;
