-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.evaluations
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    challenge_pool_user uuid NOT NULL,
    percentage smallint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT evaluations_pkey PRIMARY KEY (id),
    CONSTRAINT evaluations_challenge_pool_user_fkey FOREIGN KEY (challenge_pool_user)
        REFERENCES public.challenge_pool_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.evaluations
    OWNER to postgres;

GRANT ALL ON TABLE public.evaluations TO anon;

GRANT ALL ON TABLE public.evaluations TO authenticated;

GRANT ALL ON TABLE public.evaluations TO postgres;

GRANT ALL ON TABLE public.evaluations TO service_role;

REVOKE ALL ON TABLE public.correct_open_answers FROM anon;
REVOKE ALL ON TABLE public.correct_open_answers FROM postgres;
REVOKE ALL ON TABLE public.correct_open_answers FROM service_role;
GRANT ALL ON TABLE public.correct_open_answers TO anon;

GRANT ALL ON TABLE public.correct_open_answers TO service_role;

GRANT ALL ON TABLE public.correct_open_answers TO postgres;

REVOKE ALL ON TABLE public.challenge_pool_user FROM anon;
REVOKE ALL ON TABLE public.challenge_pool_user FROM postgres;
REVOKE ALL ON TABLE public.challenge_pool_user FROM service_role;
GRANT ALL ON TABLE public.challenge_pool_user TO anon;

GRANT ALL ON TABLE public.challenge_pool_user TO service_role;

GRANT ALL ON TABLE public.challenge_pool_user TO postgres;

REVOKE ALL ON TABLE public.invite_codes FROM anon;
REVOKE ALL ON TABLE public.invite_codes FROM postgres;
REVOKE ALL ON TABLE public.invite_codes FROM service_role;
GRANT ALL ON TABLE public.invite_codes TO anon;

GRANT ALL ON TABLE public.invite_codes TO service_role;

GRANT ALL ON TABLE public.invite_codes TO postgres;

REVOKE ALL ON TABLE public.open_feedback FROM anon;
REVOKE ALL ON TABLE public.open_feedback FROM postgres;
REVOKE ALL ON TABLE public.open_feedback FROM service_role;
GRANT ALL ON TABLE public.open_feedback TO anon;

GRANT ALL ON TABLE public.open_feedback TO service_role;

GRANT ALL ON TABLE public.open_feedback TO postgres;

REVOKE ALL ON TABLE public.open_question_drafts FROM anon;
REVOKE ALL ON TABLE public.open_question_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_question_drafts FROM service_role;
GRANT ALL ON TABLE public.open_question_drafts TO anon;

GRANT ALL ON TABLE public.open_question_drafts TO service_role;

GRANT ALL ON TABLE public.open_question_drafts TO postgres;

REVOKE ALL ON TABLE public.open_answers FROM anon;
REVOKE ALL ON TABLE public.open_answers FROM postgres;
REVOKE ALL ON TABLE public.open_answers FROM service_role;
GRANT ALL ON TABLE public.open_answers TO anon;

GRANT ALL ON TABLE public.open_answers TO service_role;

GRANT ALL ON TABLE public.open_answers TO postgres;

REVOKE ALL ON TABLE public.open_answer_drafts FROM anon;
REVOKE ALL ON TABLE public.open_answer_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_answer_drafts FROM service_role;
GRANT ALL ON TABLE public.open_answer_drafts TO anon;

GRANT ALL ON TABLE public.open_answer_drafts TO service_role;

GRANT ALL ON TABLE public.open_answer_drafts TO postgres;

REVOKE ALL ON TABLE public.open_question_topic FROM anon;
REVOKE ALL ON TABLE public.open_question_topic FROM postgres;
REVOKE ALL ON TABLE public.open_question_topic FROM service_role;
GRANT ALL ON TABLE public.open_question_topic TO anon;

GRANT ALL ON TABLE public.open_question_topic TO service_role;

GRANT ALL ON TABLE public.open_question_topic TO postgres;

REVOKE ALL ON TABLE public.open_question_likes FROM authenticated;
REVOKE ALL ON TABLE public.open_question_likes FROM postgres;
REVOKE ALL ON TABLE public.open_question_likes FROM service_role;
GRANT ALL ON TABLE public.open_question_likes TO authenticated;

GRANT ALL ON TABLE public.open_question_likes TO service_role;

GRANT ALL ON TABLE public.open_question_likes TO postgres;

REVOKE ALL ON TABLE public.open_questions FROM anon;
REVOKE ALL ON TABLE public.open_questions FROM postgres;
REVOKE ALL ON TABLE public.open_questions FROM service_role;
GRANT ALL ON TABLE public.open_questions TO anon;

GRANT ALL ON TABLE public.open_questions TO service_role;

GRANT ALL ON TABLE public.open_questions TO postgres;

REVOKE ALL ON TABLE public.open_feedback_drafts FROM anon;
REVOKE ALL ON TABLE public.open_feedback_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_feedback_drafts FROM service_role;
GRANT ALL ON TABLE public.open_feedback_drafts TO anon;

GRANT ALL ON TABLE public.open_feedback_drafts TO service_role;

GRANT ALL ON TABLE public.open_feedback_drafts TO postgres;

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO postgres;
