-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.evaluations
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    challenge_pool_user uuid NOT NULL,
    percentage smallint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT evaluations_pkey PRIMARY KEY (id),
    CONSTRAINT evaluations_challenge_pool_user_fkey FOREIGN KEY (challenge_pool_user)
        REFERENCES public.challenge_pool_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.evaluations
    OWNER to postgres;

GRANT ALL ON TABLE public.evaluations TO anon;

GRANT ALL ON TABLE public.evaluations TO authenticated;

GRANT ALL ON TABLE public.evaluations TO postgres;

GRANT ALL ON TABLE public.evaluations TO service_role;
