-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
DROP VIEW public.question_performances;

CREATE
OR REPLACE VIEW public.question_performances AS
SELECT
       course_user.id,
       questions.id AS question_id,
       questions.question_text,
       questions.created_at,
       (
              SELECT
                     count(*) AS count
              FROM
                     question_likes
              WHERE
                     question_likes.question = questions.id
       ) AS likes
FROM
       course_user
       JOIN questions ON questions.owner = course_user.user_id
       AND questions.course = course_user.course;

DROP TABLE public.correct_answers;