-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.open_question_likes
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    open_question uuid NOT NULL,
    owner uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT open_question_likes_pkey PRIMARY KEY (id),
    CONSTRAINT open_question_likes_open_question_fkey FOREIGN KEY (open_question)
        REFERENCES public.open_questions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT open_question_likes_owner_fkey FOREIGN KEY (owner)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.open_question_likes
    OWNER to postgres;

GRANT ALL ON TABLE public.open_question_likes TO authenticated;

GRANT ALL ON TABLE public.open_question_likes TO anon;

GRANT ALL ON TABLE public.open_question_likes TO service_role;

GRANT ALL ON TABLE public.open_question_likes TO postgres;

REVOKE ALL ON TABLE public.open_feedback FROM authenticated;
REVOKE ALL ON TABLE public.open_feedback FROM postgres;
REVOKE ALL ON TABLE public.open_feedback FROM service_role;
GRANT ALL ON TABLE public.open_feedback TO authenticated;

GRANT ALL ON TABLE public.open_feedback TO service_role;

GRANT ALL ON TABLE public.open_feedback TO postgres;

REVOKE ALL ON TABLE public.open_feedback_drafts FROM authenticated;
REVOKE ALL ON TABLE public.open_feedback_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_feedback_drafts FROM service_role;
GRANT ALL ON TABLE public.open_feedback_drafts TO authenticated;

GRANT ALL ON TABLE public.open_feedback_drafts TO service_role;

GRANT ALL ON TABLE public.open_feedback_drafts TO postgres;

REVOKE ALL ON TABLE public.open_question_drafts FROM authenticated;
REVOKE ALL ON TABLE public.open_question_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_question_drafts FROM service_role;
GRANT ALL ON TABLE public.open_question_drafts TO authenticated;

GRANT ALL ON TABLE public.open_question_drafts TO service_role;

GRANT ALL ON TABLE public.open_question_drafts TO postgres;

REVOKE ALL ON TABLE public.correct_open_answers FROM authenticated;
REVOKE ALL ON TABLE public.correct_open_answers FROM postgres;
REVOKE ALL ON TABLE public.correct_open_answers FROM service_role;
GRANT ALL ON TABLE public.correct_open_answers TO authenticated;

GRANT ALL ON TABLE public.correct_open_answers TO service_role;

GRANT ALL ON TABLE public.correct_open_answers TO postgres;

REVOKE ALL ON TABLE public.open_question_topic FROM authenticated;
REVOKE ALL ON TABLE public.open_question_topic FROM postgres;
REVOKE ALL ON TABLE public.open_question_topic FROM service_role;
GRANT ALL ON TABLE public.open_question_topic TO authenticated;

GRANT ALL ON TABLE public.open_question_topic TO service_role;

GRANT ALL ON TABLE public.open_question_topic TO postgres;

REVOKE ALL ON TABLE public.invite_codes FROM authenticated;
REVOKE ALL ON TABLE public.invite_codes FROM postgres;
REVOKE ALL ON TABLE public.invite_codes FROM service_role;
GRANT ALL ON TABLE public.invite_codes TO authenticated;

GRANT ALL ON TABLE public.invite_codes TO service_role;

GRANT ALL ON TABLE public.invite_codes TO postgres;

REVOKE ALL ON TABLE public.challenge_pool_user FROM authenticated;
REVOKE ALL ON TABLE public.challenge_pool_user FROM postgres;
REVOKE ALL ON TABLE public.challenge_pool_user FROM service_role;
GRANT ALL ON TABLE public.challenge_pool_user TO authenticated;

GRANT ALL ON TABLE public.challenge_pool_user TO service_role;

GRANT ALL ON TABLE public.challenge_pool_user TO postgres;

REVOKE ALL ON TABLE public.open_answers FROM authenticated;
REVOKE ALL ON TABLE public.open_answers FROM postgres;
REVOKE ALL ON TABLE public.open_answers FROM service_role;
GRANT ALL ON TABLE public.open_answers TO authenticated;

GRANT ALL ON TABLE public.open_answers TO service_role;

GRANT ALL ON TABLE public.open_answers TO postgres;

REVOKE ALL ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO service_role;

GRANT ALL ON TABLE public.profiles TO postgres;

REVOKE ALL ON TABLE public.open_answer_drafts FROM authenticated;
REVOKE ALL ON TABLE public.open_answer_drafts FROM postgres;
REVOKE ALL ON TABLE public.open_answer_drafts FROM service_role;
GRANT ALL ON TABLE public.open_answer_drafts TO authenticated;

GRANT ALL ON TABLE public.open_answer_drafts TO service_role;

GRANT ALL ON TABLE public.open_answer_drafts TO postgres;

REVOKE ALL ON TABLE public.open_questions FROM authenticated;
REVOKE ALL ON TABLE public.open_questions FROM postgres;
REVOKE ALL ON TABLE public.open_questions FROM service_role;
GRANT ALL ON TABLE public.open_questions TO authenticated;

GRANT ALL ON TABLE public.open_questions TO service_role;

GRANT ALL ON TABLE public.open_questions TO postgres;
